apiVersion: batch/v1
kind: Job
metadata:
  name: set-password-autocontroller
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  namespace: openshift-operators
spec:
  template:
    spec:
      activeDeadlineSeconds: 600
      containers:
        - image: registry.redhat.io/openshift4/ose-tools-rhel8:latest
          name: set-password
          command:
            - /bin/bash
            - -c
            - |
              set -xe
              end=$((SECONDS+60))
              while [ $SECONDS -lt $end ]; do
                secret=$(oc -n crunchy get secret autocontroller-pguser-autocontroller || true ;)
                if [ ! -z "$secret" ]; then
                # CAUTION: quick and dirty homelab stuff!
                # this needs to be different in non-playground environments. e.g. read the data from a separate secret instead
                  oc -n crunchy patch secret autocontroller-pguser-autocontroller -p='{"stringData":{"password":"autocontroller","verifier":""}}'
                  break
                else
                  echo "secret not yet there. waiting...."
                fi
              done
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: pgo
      serviceAccountName: pgo
      terminationGracePeriodSeconds: 30
